#include<stdio.h>
#include <stdlib.h>

int main()
{
    int n,i,j,a=1,m=0,k,b=0,c,d=1;
    scanf("%d",&n);
    c=n-2;
    j=n/2+1;
    b=j;
    for(i=1;i<=n;i++)
    {
        if(i<b)
        {
                for(m=2;m<=i;m++)
                    printf("---");
            if(i%2!=0)
            {
                for(k=1;k<=j;k++)
                {
                    if(k!=j)
                    {
                        printf("%d-",a);
                        a++;
                    }
                    else
                    {
                        printf("%d",a);
                    }
                }
                for(k=0;k<c;k++)
                    printf("-");
                for(k=1;k<=j;k++)
                {
                    if(k!=j)
                    {
                        printf("%d-",a);
                        a--;
                    }
                    else
                        printf("%d",a);
                }c=c-2;j--;a=a+j*2;
                printf("\n");
            }
            else
            {
                for(k=1;k<=j;k++)
                {
                    if(k!=j)
                    {
                        printf("%d-",a);
                        a--;
                    }
                    else
                        printf("%d",a);
                }
                for(k=0;k<c;k++)
                    printf("-");
                for(k=1;k<=j;k++)
                {
                    if(k!=j)
                    {
                        printf("%d-",a);
                        a++;
                    }
                    else
                        printf("%d",a);
                }
                printf("\n");c=c-2;j--;a++;
            }
        }

            if(i==b)
            {
                j=n/2+1;
                //c=n-2;
                c=0;
                for(k=1;k<j;k++)
                {
                    printf("---");
                    c=c+3;
                }
                printf("0\n");
                j=2;m=0;a=2;
            }
            if(i>b)
            {
                c=c-3;
                for(k=0;k<c;k++)
                    printf("-");
                if(m%2==0)
                {
                    for(k=1;k<=j;k++)
                    {
                        if(k!=j)
                        {
                            printf("%d-",a);
                            a--;
                        }
                        else
                            printf("%d",a);
                    }
                    for(k=1;k<=d;k++)
                    {
                        printf("-");
                    }
                    for(k=1;k<=j;k++)
                    {
                        if(k!=j)
                        {
                            printf("%d-",a);
                            a++;
                        }
                        else
                            printf("%d",a);
                    }
                    d=d+2;j++;a++;
                    printf("\n");
                    m++;
                }
                else if(m%2!=0)
                {
                    for(k=1;k<=j;k++)
                    {
                        if(k!=j)
                        {
                            printf("%d-",a);
                            a++;
                        }
                        else
                            printf("%d",a);
                    }
                    for(k=1;k<=d;k++)
                        printf("-");
                    for(k=1;k<=j;k++)
                    {
                        if(k!=j)
                        {
                            printf("%d-",a);
                            a--;
                        }
                        else
                            printf("%d",a);
                    }
                    printf("\n");m++;d=d+2;a=a+j*2;j++;
                }
            }
    }

}
